# Generated by Django 4.2.3 on 2024-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(max_length=20),
        ),
    ]
